apiVersion: v1
kind: Service
metadata:
  name: test-app-service
  labels:
    app: test-app
spec:
  type: NodePort
  selector:
    app: test-app
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  sessionAffinity: None  # Явно указываем отсутствие "прилипалки" нагрузки для корректного нагруз. теста